#!/usr/bin/env bash
# App Store / TestFlight IPA — maps key, CocoaPods, flutter build ipa.
# Requires: Xcode + Apple Developer account signed in (Settings → Accounts).
#
# Usage:
#   ./scripts/build_app_store_ipa.sh
#   ./scripts/build_app_store_ipa.sh --open-xcode   # archive in Xcode instead of CLI
set -euo pipefail

MOBILE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_ROOT/.." && pwd)"
OPEN_XCODE=false
[[ "${1:-}" == "--open-xcode" ]] && OPEN_XCODE=true

read_env() {
  local name="$1" file="$REPO_ROOT/.env.local"
  [[ -f "$file" ]] || return 0
  grep -E "^\s*${name}\s*=" "$file" 2>/dev/null | head -1 | sed -E "s/^\s*${name}\s*=\s*//" | tr -d "\"'" | sed 's/[[:space:]]*$//'
}

pod_cmd() {
  local vendor_pod="$MOBILE_ROOT/ios/vendor/bundle/ruby/2.6.0/bin/pod"
  if [[ -x "$vendor_pod" ]]; then
    export GEM_HOME="$MOBILE_ROOT/ios/vendor/bundle/ruby/2.6.0"
    export GEM_PATH="$GEM_HOME"
    export PATH="$GEM_HOME/bin:$PATH"
    echo "$vendor_pod"
    return
  fi
  if command -v pod >/dev/null 2>&1; then
    echo pod
    return
  fi
  echo ""
}

flutter_cmd() {
  local f="${FLUTTER_ROOT:-$REPO_ROOT/.flutter-sdk}/bin/flutter"
  if [[ -x "$f" ]]; then
    echo "$f"
    return
  fi
  if [[ -x /Users/macbookpro/development/flutter/bin/flutter ]]; then
    echo /Users/macbookpro/development/flutter/bin/flutter
    return
  fi
  echo flutter
}

echo "=========================================="
echo "  BytzGo — App Store IPA build"
echo "=========================================="

cd "$MOBILE_ROOT"
"$MOBILE_ROOT/scripts/validate_app_store.sh"

API_URL="$(read_env MOBILE_API_URL)"
[[ -z "$API_URL" ]] && API_URL="$(read_env VITE_API_URL)"
API_URL="${API_URL:-https://www.bytzgo.net}"
API_URL="${API_URL%/}"

if [[ -x "$(command -v node 2>/dev/null || true)" ]] && [[ -f "$MOBILE_ROOT/scripts/sync_maps_key.mjs" ]]; then
  node "$MOBILE_ROOT/scripts/sync_maps_key.mjs" 2>/dev/null || true
fi

MAPS_KEY="$(read_env GOOGLE_MAPS_API_KEY)"
[[ -z "$MAPS_KEY" ]] && MAPS_KEY="$(read_env VITE_GOOGLE_MAPS_API_KEY)"
[[ -z "$MAPS_KEY" ]] && MAPS_KEY="${GOOGLE_MAPS_API_KEY:-}"
if [[ -z "$MAPS_KEY" ]] && command -v curl >/dev/null 2>&1; then
  MAPS_KEY="$(curl -fsSL "${API_URL}/api/config/maps" 2>/dev/null | sed -n 's/.*"apiKey":"\([^"]*\)".*/\1/p' || true)"
fi
if [[ -z "$MAPS_KEY" ]]; then
  echo "WARN: No GOOGLE_MAPS_API_KEY — maps may be blank until runtime /api/config/maps."
fi

GOOGLE_CLIENT="$(read_env GOOGLE_WEB_CLIENT_ID)"
[[ -z "$GOOGLE_CLIENT" ]] && GOOGLE_CLIENT="$(read_env VITE_GOOGLE_CLIENT_ID)"
GOOGLE_CLIENT="${GOOGLE_CLIENT:-645977332644-4gjjf08268b3irafs4bh8b7guct1i1jb.apps.googleusercontent.com}"

DEFINES="$MOBILE_ROOT/dart_defines.json"
cat > "$DEFINES" <<EOF
{
  "API_URL": "$API_URL",
  "GOOGLE_WEB_CLIENT_ID": "$GOOGLE_CLIENT",
  "GOOGLE_MAPS_API_KEY": "$MAPS_KEY"
}
EOF

if [[ -n "$MAPS_KEY" ]]; then
  cat > "$MOBILE_ROOT/lib/core/maps_key.dart" <<EOF
/// Auto-generated by scripts/build_app_store_ipa.sh — do not commit secrets.
class MapsKey {
  MapsKey._();
  static const String resolved = '$MAPS_KEY';
}
EOF
  mkdir -p "$MOBILE_ROOT/ios/Runner"
  cat > "$MOBILE_ROOT/ios/Runner/MapsConfig.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>GOOGLE_MAPS_API_KEY</key>
	<string>$MAPS_KEY</string>
</dict>
</plist>
EOF
fi

FLUTTER="$(flutter_cmd)"
echo "→ Version: $(grep '^version:' pubspec.yaml)"
echo "→ API_URL=$API_URL"
echo "→ flutter: $FLUTTER"

"$FLUTTER" pub get

POD="$(pod_cmd)"
if [[ -z "$POD" ]]; then
  echo "ERROR: CocoaPods not found. Install: gem install cocoapods --user-install"
  echo "       or restore mobile/ios/vendor/ from the repo."
  exit 1
fi

echo "→ pod install ($POD)"
(cd ios && "$POD" install)

if $OPEN_XCODE; then
  echo "→ Opening Xcode — use Product → Archive → Distribute to App Store Connect"
  open "$MOBILE_ROOT/ios/Runner.xcworkspace"
  exit 0
fi

echo "→ flutter build ipa (release)"
"$FLUTTER" build ipa --release --dart-define-from-file=dart_defines.json

IPA_DIR="$MOBILE_ROOT/build/ios/ipa"
if compgen -G "$IPA_DIR"/*.ipa >/dev/null 2>&1; then
  IPA="$(ls -1 "$IPA_DIR"/*.ipa | head -1)"
  echo ""
  echo "=========================================="
  echo "  SUCCESS"
  echo "  $IPA"
  echo "=========================================="
  echo "Upload with Transporter app or:"
  echo "  open -a Transporter \"$IPA\""
  if [[ -d /Applications/Transporter.app ]]; then
    open -a Transporter "$IPA" 2>/dev/null || true
  fi
else
  echo ""
  echo "IPA build failed (usually Xcode signing)."
  echo "1. Open Xcode → Settings → Accounts → add your Apple ID"
  echo "2. Run:  ./scripts/build_app_store_ipa.sh --open-xcode"
  echo "3. Product → Archive → Distribute App → App Store Connect"
  open "$MOBILE_ROOT/ios/Runner.xcworkspace"
  exit 1
fi
