#!/usr/bin/env bash
# Build release APK (Linux/macOS). Mirrors build_apk.ps1.
set -euo pipefail

MOBILE_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO_ROOT="$(cd "$MOBILE_ROOT/.." && pwd)"
API_URL="${1:-}"

read_env() {
  local name="$1" file="$REPO_ROOT/.env.local"
  [[ -f "$file" ]] || return 0
  grep -E "^\s*${name}\s*=" "$file" 2>/dev/null | head -1 | sed -E "s/^\s*${name}\s*=\s*//" | tr -d "\"'" | sed 's/[[:space:]]*$//'
}

if [[ -z "$API_URL" ]]; then
  API_URL="$(read_env MOBILE_API_URL)"
fi
if [[ -z "$API_URL" ]]; then
  API_URL="$(read_env VITE_API_URL)"
fi
API_URL="${API_URL:-https://www.bytzgo.net}"
API_URL="${API_URL%/}"

if [[ -x "$(command -v node)" ]] && [[ -f "$MOBILE_ROOT/scripts/sync_maps_key.mjs" ]]; then
  node "$MOBILE_ROOT/scripts/sync_maps_key.mjs" || true
fi

MAPS_KEY="$(read_env GOOGLE_MAPS_API_KEY)"
if [[ -z "$MAPS_KEY" ]]; then
  MAPS_KEY="$(read_env VITE_GOOGLE_MAPS_API_KEY)"
fi
if [[ -z "$MAPS_KEY" ]]; then
  MAPS_KEY="${GOOGLE_MAPS_API_KEY:-}"
fi
if [[ -z "$MAPS_KEY" ]] && [[ -f "$MOBILE_ROOT/lib/core/maps_key.dart" ]]; then
  MAPS_KEY="$(grep -oE "resolved = '[^']+'" "$MOBILE_ROOT/lib/core/maps_key.dart" | sed "s/.*'\\([^']*\\)'.*/\\1/" || true)"
fi

GOOGLE_CLIENT="$(read_env GOOGLE_WEB_CLIENT_ID)"
if [[ -z "$GOOGLE_CLIENT" ]]; then
  GOOGLE_CLIENT="$(read_env VITE_GOOGLE_CLIENT_ID)"
fi
GOOGLE_CLIENT="${GOOGLE_CLIENT:-645977332644-4gjjf08268b3irafs4bh8b7guct1i1jb.apps.googleusercontent.com}"

DEFINES="$MOBILE_ROOT/dart_defines.json"
cat > "$DEFINES" <<EOF
{
  "API_URL": "$API_URL",
  "GOOGLE_WEB_CLIENT_ID": "$GOOGLE_CLIENT",
  "GOOGLE_MAPS_API_KEY": "$MAPS_KEY"
}
EOF

if [[ -n "$MAPS_KEY" ]]; then
  cat > "$MOBILE_ROOT/lib/core/maps_key.dart" <<EOF
/// Auto-generated by scripts/build_apk.sh
class MapsKey {
  MapsKey._();
  static const String resolved = '$MAPS_KEY';
}
EOF
  LOCAL_PROPS="$MOBILE_ROOT/android/local.properties"
  touch "$LOCAL_PROPS"
  grep -v '^\s*GOOGLE_MAPS_API_KEY\s*=' "$LOCAL_PROPS" > "${LOCAL_PROPS}.tmp" 2>/dev/null || true
  mv "${LOCAL_PROPS}.tmp" "$LOCAL_PROPS" 2>/dev/null || touch "$LOCAL_PROPS"
  echo "GOOGLE_MAPS_API_KEY=$MAPS_KEY" >> "$LOCAL_PROPS"
fi

FLUTTER="${FLUTTER_ROOT:-$REPO_ROOT/.flutter-sdk}/bin/flutter"
if [[ ! -x "$FLUTTER" ]]; then
  FLUTTER="flutter"
fi

echo "BytzGo APK — API_URL=$API_URL"
cd "$MOBILE_ROOT"
"$FLUTTER" pub get
"$FLUTTER" build apk --release --dart-define-from-file=dart_defines.json

node "$REPO_ROOT/scripts/copy-apk-to-public.mjs"
echo ""
echo "APK ready:"
echo "  $MOBILE_ROOT/build/app/outputs/flutter-apk/app-release.apk"
echo "  $REPO_ROOT/public/bytzgo.apk"
