#!/usr/bin/env node
/**
 * Sync GOOGLE_MAPS_API_KEY into Android, iOS, and Dart (cross-platform).
 * Sources (first match): env, repo .env.local, production GET /api/config/maps
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const mobileRoot = path.resolve(__dirname, '..');
const repoRoot = path.resolve(mobileRoot, '..');
const envFile = path.join(repoRoot, '.env.local');

function readEnvFile() {
  if (!fs.existsSync(envFile)) return '';
  return fs.readFileSync(envFile, 'utf8');
}

function keyFromEnvFile(text) {
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^(?:GOOGLE_MAPS_API_KEY|VITE_GOOGLE_MAPS_API_KEY)\s*=\s*(.+)\s*$/);
    if (m) return m[1].trim().replace(/^["']|["']$/g, '');
  }
  return '';
}

function readEnvLine(text, name) {
  const re = new RegExp(`^\\s*${name}\\s*=\\s*(.+)\\s*$`);
  for (const line of text.split(/\r?\n/)) {
    const m = line.trim().match(re);
    if (m) return m[1].trim().replace(/^["']|["']$/g, '');
  }
  return '';
}

async function keyFromProduction() {
  const bases = [
    process.env.API_URL?.replace(/\/$/, ''),
    process.env.MOBILE_API_URL?.replace(/\/$/, ''),
    'https://www.bytzgo.net',
  ].filter(Boolean);
  for (const base of bases) {
    try {
      const res = await fetch(`${base}/api/config/maps`, {
        headers: { Accept: 'application/json' },
      });
      if (!res.ok) continue;
      const data = await res.json();
      const key = String(data.apiKey || '').trim();
      if (key.length >= 20 && key.startsWith('AIza')) return key;
    } catch {
      /* try next base */
    }
  }
  return '';
}

async function resolveKey() {
  const fromEnv = String(process.env.GOOGLE_MAPS_API_KEY || process.env.VITE_GOOGLE_MAPS_API_KEY || '').trim();
  if (fromEnv.length >= 20) return fromEnv;
  const text = readEnvFile();
  const fromFile = keyFromEnvFile(text);
  if (fromFile.length >= 20) return fromFile;
  return keyFromProduction();
}

function defaultApiUrlFromEnvFile(text) {
  let url = readEnvLine(text, 'MOBILE_API_URL');
  if (!url) url = readEnvLine(text, 'VITE_API_URL');
  if (!url) return 'https://www.bytzgo.net';
  url = url.replace(/\/$/, '');
  if (/^(https?:\/\/)?(localhost|127\.0\.0\.1)(:\d+)?$/i.test(url)) {
    return 'https://www.bytzgo.net';
  }
  return url;
}

function defaultGoogleClientFromEnvFile(text) {
  return (
    readEnvLine(text, 'GOOGLE_WEB_CLIENT_ID') ||
    readEnvLine(text, 'VITE_GOOGLE_CLIENT_ID') ||
    '645977332644-4gjjf08268b3irafs4bh8b7guct1i1jb.apps.googleusercontent.com'
  );
}

function writeLocalProperties(key) {
  const localProps = path.join(mobileRoot, 'android', 'local.properties');
  let lines = [];
  if (fs.existsSync(localProps)) {
    lines = fs
      .readFileSync(localProps, 'utf8')
      .split(/\r?\n/)
      .filter((l) => !/^\s*GOOGLE_MAPS_API_KEY\s*=/.test(l));
  }
  lines.push(`GOOGLE_MAPS_API_KEY=${key}`);
  const flutterSdk = path.join(repoRoot, '.flutter-sdk');
  if (fs.existsSync(path.join(flutterSdk, 'bin', 'flutter'))) {
    const flutterLine = `flutter.sdk=${flutterSdk.replace(/\\/g, '\\\\')}`;
    if (!lines.some((l) => /^\s*flutter\.sdk\s*=/.test(l))) lines.push(flutterLine);
  }
  const androidSdk = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
  if (androidSdk && !lines.some((l) => /^\s*sdk\.dir\s*=/.test(l))) {
    lines.push(`sdk.dir=${androidSdk.replace(/\\/g, '\\\\')}`);
  }
  fs.writeFileSync(localProps, `${lines.filter(Boolean).join('\n')}\n`, 'utf8');
  console.log('Updated android/local.properties');
}

function writeIosMapsConfig(key) {
  const plistPath = path.join(mobileRoot, 'ios', 'Runner', 'MapsConfig.plist');
  fs.mkdirSync(path.dirname(plistPath), { recursive: true });
  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>API_KEY</key>
	<string>${key}</string>
</dict>
</plist>
`;
  fs.writeFileSync(plistPath, xml, 'utf8');
  console.log('Updated ios/Runner/MapsConfig.plist');
}

function updateIosInfoPlist(key) {
  const infoPath = path.join(mobileRoot, 'ios', 'Runner', 'Info.plist');
  if (!fs.existsSync(infoPath)) return;
  let xml = fs.readFileSync(infoPath, 'utf8');
  if (!xml.includes('<key>GMSApiKey</key>')) return;
  xml = xml.replace(/(<key>GMSApiKey<\/key>\s*<string>)[^<]*(<\/string>)/, `$1${key}$2`);
  fs.writeFileSync(infoPath, xml, 'utf8');
  console.log('Updated ios/Runner/Info.plist GMSApiKey');
}

function writeMapsKeyDart(key) {
  const dartPath = path.join(mobileRoot, 'lib', 'core', 'maps_key.dart');
  const content = `/// Auto-generated by scripts/sync_maps_key.mjs — do not commit real keys in public forks.
class MapsKey {
  MapsKey._();
  static const String resolved = '${key.replace(/'/g, "\\'")}';
}
`;
  fs.writeFileSync(dartPath, content, 'utf8');
  console.log('Updated lib/core/maps_key.dart');
}

function mergeDartDefines(key) {
  const definesPath = path.join(mobileRoot, 'dart_defines.json');
  const envText = readEnvFile();
  const defaults = {
    GOOGLE_MAPS_API_KEY: key,
    API_URL: defaultApiUrlFromEnvFile(envText),
    GOOGLE_WEB_CLIENT_ID: defaultGoogleClientFromEnvFile(envText),
  };
  let defines = { ...defaults };
  if (fs.existsSync(definesPath)) {
    try {
      const existing = JSON.parse(fs.readFileSync(definesPath, 'utf8'));
      defines = { ...defaults, ...existing, GOOGLE_MAPS_API_KEY: key };
    } catch {
      defines = defaults;
    }
  }
  fs.writeFileSync(definesPath, `${JSON.stringify(defines, null, 2)}\n`, 'utf8');
  console.log('Updated dart_defines.json');
}

const key = await resolveKey();
if (!key || key.length < 20 || !key.startsWith('AIza')) {
  console.error('No valid GOOGLE_MAPS_API_KEY (set env, .env.local, or deploy backend /api/config/maps)');
  process.exit(1);
}
console.log(`Maps key …${key.slice(-6)}`);
writeLocalProperties(key);
writeIosMapsConfig(key);
updateIosInfoPlist(key);
writeMapsKeyDart(key);
mergeDartDefines(key);
