import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Firebase project **bytzgo-9bd89** — generated by setup-firebase-android.mjs
class DefaultFirebaseOptions {
  static const bool isConfigured = true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Firebase is not supported on this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8nNArzYmjNfYsgKQzDSxlwcAfH2iTtiY',
    appId: '1:645977332644:android:c61f7624820fc1e2977f31',
    messagingSenderId: '645977332644',
    projectId: 'bytzgo-9bd89',
    storageBucket: 'bytzgo-9bd89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzDpvnJJ6x4zThAMk95KD_ABCF8Eo9ixY',
    appId: '1:645977332644:ios:0b014667ec40000e977f31',
    messagingSenderId: '645977332644',
    projectId: 'bytzgo-9bd89',
    storageBucket: 'bytzgo-9bd89.firebasestorage.app',
    iosBundleId: 'com.bytzgo.bytzgoMobile',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8nNArzYmjNfYsgKQzDSxlwcAfH2iTtiY',
    appId: '1:645977332644:android:c61f7624820fc1e2977f31',
    messagingSenderId: '645977332644',
    projectId: 'bytzgo-9bd89',
    storageBucket: 'bytzgo-9bd89.firebasestorage.app',
  );
}
